apiVersion: v1
kind: Pod
metadata:
  name: devpod-placeholder
spec:
  containers:
    - name: devbox
      resources:
        limits:
          nvidia.com/gpu: "1"
          memory: "256Gi"
          cpu: "32"
        requests:
          nvidia.com/gpu: "1"
          memory: "256Gi"
          cpu: "32"
      securityContext:
        privileged: true
      volumeMounts:
        - name: dshm
          mountPath: /dev/shm
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 64Gi
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
